### ISSUE TITLE
延迟队列

### ISSUE THREAD

**Issue by roneywei** [apache/rocketmq-spring#166]
demo里面没有涉及延迟队列的使用，建议增加延迟队列的demo

**Comment by RongtongJin** [comment]
Do you mean scheduled message ?  You can set delay level with syncSend method to use scheduled message.
https://github.com/apache/rocketmq-spring/blob/e10cc5e68ff42cb5693655186734677d8df0d7cd/rocketmq-spring-boot/src/main/java/org/apache/rocketmq/spring/core/RocketMQTemplate.java#L175

**Comment by roneywei** [comment]
我利用RocketMQTemplate.java发送延迟消息
demo如下
@Test
    public void syncDelayQueue() {
     
        String messageContent = "syncDelayQueue";
        Map h = new ConcurrentHashMap();
        h.put("message", messageContent);
        h.put("defaultQueue", syncDelayQueue);
        Message<?> message = MessageBuilder
                .withPayload(JSON.toJSON(h))
                .setHeader("contentType", "application/json")
                .build();

        producer.syncDelayQueue(message, MessageDelayLevel.ONE_S);

     

    }

public void syncDelayQueue(Message<?> message, MessageDelayLevel messageDelayLevel) {
        log.info("send syncDelayQueue message :{};rocketMqDelayLevel:{}", message, messageDelayLevel);
        this.rocketMqUtils.syncDelayQueue(syncDelayQueue, message, messageDelayLevel);
    }

 public SendResult syncDelayQueue(String queueName, Message<?> message, MessageDelayLevel messageDelayLevel)  {
        log.info("syncDelayQueue queueName:{},message:{},delayLevel:{}", queueName, message, messageDelayLevel);
        SendResult result = rocketMQTemplate.syncSend(queueName, message,  rocketMQTemplate.getProducer().getSendMsgTimeout(), messageDelayLevel.getValue());
        log.info("syncDelayQueue result:{}",result);
        return result;
    }

我发送的是org.springframework.messaging.Message

请问一下，我怎样直接接收org.springframework.messaging.Message发送的内容

 @Component
    @RocketMQMessageListener(topic =  "${mq.demo.sync-delay-queue:syncDelayQueueDemo}",consumerGroup = "demo")
    class SyncDelayQueueDemo  implements RocketMQListener<Message> {
        @Override
        public void onMessage( Message message) {

            log.info("RocketMqConsumer1 syncDelayQueueDemo message :{} " ,message);
        }
    }

错误信息如下：

java.lang.RuntimeException: cannot convert message to interface org.springframework.messaging.Message
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.doConvertMessage(DefaultRocketMQListenerContainer.java:382)
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.access$100(DefaultRocketMQListenerContainer.java:57)
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer$DefaultMessageListenerConcurrently.consumeMessage(DefaultRocketMQListenerContainer.java:330)
	at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:411)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by RongtongJin** [comment]
延迟消息与consumer端的接收无关。consumer端只需遵循demo中的示例正常接收。你可以接收MessageExt（RocketMQ的消息类型）类型、String类型或者发送的对象类型，不要去直接接收org.springframework.messaging.Message类型。
