### ISSUE TITLE
: could not initialize proxy [cloud.formu.pay.model.PaymentOrder#231851604414824448] - no Session

### ISSUE THREAD

**Issue by xunianchong** [apache/rocketmq-spring#185]
和spring boot jpa集成后，监听类调用hibernate 出现无事务，这个估计得你们解决哈

**Comment by RongtongJin** [comment]
Could you give more details such as some important log? And why do you think rocketmq-spring affects this issue？

**Comment by xunianchong** [comment]
![image](https://user-images.githubusercontent.com/16568795/70126599-58ebe380-16b4-11ea-90ad-3c6d8425aaec.png)
![image](https://user-images.githubusercontent.com/16568795/70126645-6903c300-16b4-11ea-966c-3a98879ccdc5.png)
user spring boot

**Comment by xunianchong** [comment]
could not initialize proxy [cloud.formu.pay.model.PaymentOrder#233652582931759104] - no Session
	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:169) ~[hibernate-core-5.3.11.Final.jar:5.3.11.Final]
	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:309) ~[hibernate-core-5.3.11.Final.jar:5.3.11.Final]
	at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor.intercept(ByteBuddyInterceptor.java:45) ~[hibernate-core-5.3.11.Final.jar:5.3.11.Final]
	at org.hibernate.proxy.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:95) ~[hibernate-core-5.3.11.Final.jar:5.3.11.Final]
	at cloud.formu.pay.model.PaymentOrder$HibernateProxy$eVN7tjOG.getNotifyUrl(Unknown Source) ~[classes/:na]
	at cloud.formu.pay.listen.PayNofityBuzListener.onMessage(PayNofityBuzListener.java:47) ~[classes/:na]
	at cloud.formu.pay.listen.PayNofityBuzListener.onMessage(PayNofityBuzListener.java:23) ~[classes/:na]
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer$DefaultMessageListenerConcurrently.consumeMessage(DefaultRocketMQListenerContainer.java:350) ~[rocketmq-spring-boot-2.0.4.jar:2.0.4]
	at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:411) [rocketmq-client-4.5.2.jar:4.5.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]


`   PaymentOrder paymentOrder =  jdbcTemplate.queryForObject("select * from p_order where payment_order_no='"+paymentOrderQueryResponse.getTradeNo()+"'",new BeanPropertyRowMapper<>(PaymentOrder.class));
        // PaymentOrder paymentOrder = paymentOrderService.getPaymentOrderByPaymentOrderNo(paymentOrderQueryResponse.getTradeNo());
        if(paymentOrder == null){
            throw new MessageReceiveException("not found paymentOrder by paymentOrderNo "+paymentOrderQueryResponse.getTradeNo());
        }
        paymentActionManager.notfiyPayOrderAction(paymentOrderQueryResponse.getTradeNo(),"支付完成，开始通知客户",null);
       try {
           if(StringUtils.isBlank(paymentOrder.getNotifyUrl())){`

**Comment by RongtongJin** [comment]
From the code and log you gave, I'm not sure it was rocketmq-spring that caused this error.
