### ISSUE TITLE
create reply message fail, requestMessage error, property[CLUSTER] is null.

### ISSUE THREAD

**Issue by wdreamsky** [apache/rocketmq-spring#300]
org.apache.rocketmq.client.exception.MQClientException: CODE: 10007  DESC: create reply message fail, requestMessage error, property[CLUSTER] is null.
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.utils.MessageUtil.createReplyMessage(MessageUtil.java:46)
	at com.kangma.mq.support.DefaultRocketMQListenerContainer.handleMessage(DefaultRocketMQListenerContainer.java:395)
	at com.kangma.mq.support.DefaultRocketMQListenerContainer.access$100(DefaultRocketMQListenerContainer.java:66)
	at com.kangma.mq.support.DefaultRocketMQListenerContainer$DefaultMessageListenerConcurrently.consumeMessage(DefaultRocketMQListenerContainer.java:350)
	at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:412)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by RongtongJin** [comment]
The isssue has been sloved in this [PR](https://github.com/apache/rocketmq/pull/1902). Plz upgrade your rocketmq broker version to 4.7.1.

**Comment by wdreamsky** [comment]
> The isssue has been sloved in this [PR](https://github.com/apache/rocketmq/pull/1902). Plz upgrade your rocketmq broker version to 4.7.1.

![image](https://user-images.githubusercontent.com/7259609/99870608-78568600-2c0f-11eb-9a50-1bc4d26ab72a.png)
