### ISSUE TITLE
TransactionListener not found 

### ISSUE THREAD

**Issue by lwanqiang** [apache/rocketmq-spring#31]
本地测试在idea下测试正常，而打包后调用
Caused by: java.lang.NoClassDefFoundError: org/apache/rocketmq/client/producer/TransactionListener
        at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSend(RocketMQTemplate.java:142)
        at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSend(RocketMQTemplate.java:122)
        at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSend(RocketMQTemplate.java:178)
        at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSend(RocketMQTemplate.java:165)

**Comment by lwanqiang** [comment]
jar冲突
