### ISSUE TITLE
RocketMQListener support list  covert error

### ISSUE THREAD

**Issue by moses-keqi** [apache/rocketmq-spring#407]
`package com.xxx.application.handle;

import com.xxx.application.log.TaskLogDetailEvent;
import lombok.extern.slf4j.Slf4j;
import org.apache.rocketmq.spring.annotation.ConsumeMode;
import org.apache.rocketmq.spring.annotation.RocketMQMessageListener;
import org.apache.rocketmq.spring.core.RocketMQListener;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * @author 
 * @Date 2021/11/18 1:56 下午
 * @Version 1.0
 */
@Slf4j
@Component
@RocketMQMessageListener(consumerGroup = "${rocketmq.consumer.group}", topic = "tasklogdetailevent-test", consumeMode = ConsumeMode.ORDERLY)
public class TestLogListener implements RocketMQListener<List<TaskLogDetailEvent>> {
    @Override
    public void onMessage(List<TaskLogDetailEvent> taskLogDetailEvents) {

//        String s = JSON.toJSONString(taskLogDetailEvents);
//        taskLogDetailEvents =  JSON.parseArray(s, TaskLogDetailEvent.class);
        System.out.println(1111);

    }
}
`

2.3.4.RELEASE  DefaultRocketMQListenerContainer  getMessageType  covert error

Caused by: java.lang.ClassCastException: sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.getMessageType(DefaultRocketMQListenerContainer.java:381)
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.afterPropertiesSet(DefaultRocketMQListenerContainer.java:277)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
	... 21 common frames omitted

**Comment by moses-keqi** [comment]
最后发现原来引入maven  自身除了问题
![Uploading WeChat6b08410c96a5032848807a9302607054.png…](https://img-blog.csdnimg.cn/776c0bed010640619e39a8ad5a80a7c3.png)
