### ISSUE TITLE
 invokeSync call timeout

### ISSUE THREAD

**Issue by wangqingchengsg** [apache/rocketmq-spring#485]
rocketmq-spring-boot-starter 版本 2.2.2
rocketmq搭建环境 rocketmq-4.9.3

报错信息如下
Caused by: org.apache.rocketmq.remoting.exception.RemotingTimeoutException: invokeSync call timeout
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:375) ~[rocketmq-remoting-4.9.1.jar:4.9.1]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1365) ~[rocketmq-client-4.9.1.jar:4.9.1]
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1355) ~[rocketmq-client-4.9.1.jar:4.9.1]
	at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:622) ~[rocketmq-client-4.9.1.jar:4.9.1]
	... 50 common frames omitted

**Comment by panzhi33** [comment]
The network has timed out, you can check the network status at that time

**Comment by francisoliverlee** [comment]
可以先ping下namesrv是否可达， 可达的话多半是网络慢， 此时可以尝试调大 mqClientApiTimeout
