### ISSUE TITLE
onMessage ClassCastException in abstract class implements RocketMQListener<String> 

### ISSUE THREAD

**Issue by hezhihua73** [apache/rocketmq-spring#561]
### stack_trace
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.String
	at com.evatmaster.biz.center.order.listener.BaseStringMQListener.onMessage(BaseStringMQListener.java:9)
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer$DefaultMessageListenerConcurrently.consumeMessage$original$QpHFUl6E(DefaultRocketMQListenerContainer.java:295)
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer$DefaultMessageListenerConcurrently.consumeMessage$original$QpHFUl6E$accessor$mAN1OZPY(DefaultRocketMQListenerContainer.java)
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer$DefaultMessageListenerConcurrently$auxiliary$Nka19xia.call(Unknown Source)
	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer$DefaultMessageListenerConcurrently.consumeMessage(DefaultRocketMQListenerContainer.java)
	at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:417)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
--

### logger_message

consume message failed. messageExt:MessageExt [queueId=0, storeSize=747, queueOffset=97, sysFlag=0, bornTimestamp=1684410538674, bornHost=/172.30.113.163:57632, storeTimestamp=1684411178723, storeHost=/172.30.13.248:10911, msgId=AC1E0DF800002A9F0000002F2FBA358E, commitLogOffset=202664195470, bodyCRC=1155098648, reconsumeTimes=6, preparedTransactionOffset=0, toString()=Message{topic='order_to_be_paid', flag=0, properties={USERS_id=25a15e2b-72c5-4373-8ed9-143addfafd81, CONSUME_START_TIME=1684411178724, MIN_OFFSET=0, REAL_TOPIC=%RETRY%order_to_be_paid, sw8-x=0-1684410538674, ORIGIN_MESSAGE_ID=AC1E0DF800002A9F0000002F2FA36647, USERS_timestamp=1684410538674, sw8=1-NGVkNGEyNmJlZTA0NDcyOGIxYzk2MDJjMmIxZDg2MmUuNzIuMTY4NDQxMDUzODYxOTM0MDc=-NjY3MmRlMTQyMTdlNDg5YWJjY2Q1ZmNlNzQwZjlkM2QuMTA1LjE2ODQ0MTA1Mzg2MjIzMzQ0-57-Y2VudGVyOjpzdmMtYml6LWNlbnRlcg==-MTcyLjMwLjExMy4xNjM=-UE9TVDovbWVyYy9vcmRlci9jcmVhdGU=-cHJvZC1tcW5hbWVzcnYucHJvZC5zdmMuY2x1c3Rlci5sb2NhbDo5ODc2, RETRY_TOPIC=order_to_be_paid, MAX_OFFSET=98, UNIQ_KEY=AC1E71A3000109573B3B5BCCA6B20011, WAIT=false, DELAY=8, REAL_QID=0}, body=[123, 34, 111, 114, 100, 101, 114, 73, 100, 34, 58, 49, 54, 53, 57, 49, 54, 52, 49, 55, 48, 51, 54, 54, 52, 56, 56, 53, 55, 55, 44, 34, 115, 121, 115, 116, 101, 109, 84, 121, 112, 101, 34, 58, 34, 48, 48, 34, 125], transactionId='null'}]
--

![BaseStringMQListener](https://github.com/apache/rocketmq-spring/assets/47775252/f1b1a9f7-d0e6-493b-84de-280b7438564f)
![consumeMessage](https://github.com/apache/rocketmq-spring/assets/47775252/692dc4d2-cda1-43c3-b2f9-788717700782)

maven version
  rocketmq-spring-boot-starter 2.0.1
--

**Comment by hezhihua73** [comment]
![Exception](https://github.com/apache/rocketmq-spring/assets/47775252/a17fd91b-25c5-45c0-9459-418af47e5b6a)

**Comment by einsitang** [comment]
你的问题应该就是`doConvertMessage(messageExt)`没有找到正确的反序列化方法，所以识别成LinkHashMap，之后调用你的`BaseStringMQListener.onMessage` 方法，所以就报转换错误
```
java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.String
at com.evatmaster.biz.center.order.listener.BaseStringMQListener.onMessage(BaseStringMQListener.java:9)
```
你的message信息是：{"orderId":1659164170366488577,"systemType":"00"}
发送的时候明确转换成json string则应该是："{\"orderId\":1659164170366488577,\"systemType\":\"00\"}"
那么他就可以识别了。

不过奇怪的是，为什么行号是错误的 `BaseStringMQListener.java:9`

**Comment by hezhihua73** [comment]
> 你的问题应该就是没有找到正确的反序列化方法，所以识别成LinkHashMap，之后调用你的 方法，所以就报转换错误`doConvertMessage(messageExt)``BaseStringMQListener.onMessage`
> 
> ```
> java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.String
> at com.evatmaster.biz.center.order.listener.BaseStringMQListener.onMessage(BaseStringMQListener.java:9)
> ```
> 
> 你的message信息是：{"orderId":1659164170366488577,"systemType":"00"} 发送的时候明确转换成json string则应该是："{\"orderId\":1659164170366488577,\"systemType\":\"00\"}" 那么他就可以识别了。
> 
> 不过奇怪的是，为什么行号是错误的 `BaseStringMQListener.java:9`

原来我的思路也是你这样，因为LinkHashMap转String错误异常是很典型的jackson在找不到序列化类型的时候基础转换错误；但是进入doConvertMessage之后会发现，消息序列化转换的类型是messageType，也就是对RocketMQListener实现BaseStringMQListener定义的泛型<String>,按照这个预期的话就不会有这个问题，非常的令人疑惑

**Comment by justToBeGood** [comment]
org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer#messageConverter

**Comment by justToBeGood** [comment]
如果messageType是String，就直接返回，不会走序列化的逻辑才是
![image](https://github.com/apache/rocketmq-spring/assets/50023670/41b7738c-98e9-4ecd-8f86-7fcdfc6f3e60)

**Comment by hezhihua73** [comment]
按照预期是这样的，以前也一直都运行正常，就突然开始全面报错

**Comment by hezhihua73** [comment]
> 如果messageType是String，就直接返回，不会走序列化的逻辑才是 ![image](https://user-images.githubusercontent.com/50023670/256148646-41b7738c-98e9-4ecd-8f86-7fcdfc6f3e60.png)

按照预期是这样的，以前也一直都运行正常，就突然开始全面报错

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Under Review**

This issue has been identified as a potential bug. It will be analyzed against the codebase to verify the reported behavior.

If you have additional information (version, reproduction steps, logs), please share it to help speed up the verification.

---
*Automated evaluation by github-manager-bot*
