### ISSUE TITLE
Commands not working for creating the topics

### ISSUE THREAD

**Issue by AayushSaini101** [apache/rocketmq-spring#576]
Please describe the issue you observed:

The following commands for creating the topics in RocketMQ are not working and need to update.

```
bash bin/mqadmin updateTopic -c DefaultCluster -t string-topic
bash bin/mqadmin updateTopic -c DefaultCluster -t order-paid-topic
bash bin/mqadmin updateTopic -c DefaultCluster -t message-ext-topic
bash bin/mqadmin updateTopic -c DefaultCluster -t spring-transaction-topic
```
Error Log: While creating the topics using above command 

```
mac rocketmq-all-5.0.0-bin-release %  bin/mqadmin updateTopic -c DefaultCluster -t string-topic                     
org.apache.rocketmq.tools.command.SubCommandException: UpdateTopicSubCommand command failed
	at org.apache.rocketmq.tools.command.topic.UpdateTopicSubCommand.execute(UpdateTopicSubCommand.java:198)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main0(MQAdminStartup.java:165)
	at org.apache.rocketmq.tools.command.MQAdminStartup.main(MQAdminStartup.java:114)
Caused by: org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to null failed
	at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:473)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.getBrokerClusterInfo(MQClientAPIImpl.java:1755)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExtImpl.examineBrokerClusterInfo(DefaultMQAdminExtImpl.java:556)
	at org.apache.rocketmq.tools.admin.DefaultMQAdminExt.examineBrokerClusterInfo(DefaultMQAdminExt.java:307)
	at org.apache.rocketmq.tools.command.CommandUtil.fetchMasterAddrByClusterName(CommandUtil.java:95)
	at org.apache.rocketmq.tools.command.topic.UpdateTopicSubCommand.execute(UpdateTopicSubCommand.java:171)
	... 2 more
```
The DefaultCluster need to replace with the proper address and port number is:

```
mac rocketmq-all-5.0.0-bin-release % bin/mqadmin updateTopic -n localhost:9876 -b 192.168.1.8:10911 -t rocketMQ
create topic to 192.168.1.8:10911 success.
TopicConfig [topicName=rocketMQ, readQueueNums=8, writeQueueNums=8, perm=RW-, topicFilterType=SINGLE_TAG, topicSysFlag=0, order=false, attributes={}]% 
```

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Under Review**

This issue has been identified as a potential bug. It will be analyzed against the codebase to verify the reported behavior.

If you have additional information (version, reproduction steps, logs), please share it to help speed up the verification.

---
*Automated evaluation by github-manager-bot*
