### ISSUE TITLE
JDK17 + Springboot3 +rocketmq-spring-boot-starter2.2.3启动报错

### ISSUE THREAD

**Issue by shen-hong-wei** [apache/rocketmq-spring#603]
报错信息如下：
2023-12-06 17:22:27.410 INFO  [traceId-] [spanId-]  [org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger:82] [main] o.s.b.a.logging.ConditionEvaluationReportLogger - 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-12-06 17:22:27.422 ERROR [traceId-] [spanId-]  [org.springframework.boot.SpringApplication:824] [main] org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer_1': org/apache/rocketmq/common/protocol/heartbeat/MessageModel
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1161)
	at org.apache.rocketmq.spring.autoconfigure.ListenerContainerConfiguration.registerContainer(ListenerContainerConfiguration.java:116)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at org.apache.rocketmq.spring.autoconfigure.ListenerContainerConfiguration.afterSingletonsInstantiated(ListenerContainerConfiguration.java:79)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:984)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.chinamobile.cmss.dsp.data.DataApplication.main(DataApplication.java:26)
Caused by: java.lang.NoClassDefFoundError: org/apache/rocketmq/common/protocol/heartbeat/MessageModel
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.initRocketMQPushConsumer(DefaultRocketMQListenerContainer.java:644)
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.afterPropertiesSet(DefaultRocketMQListenerContainer.java:369)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
	... 20 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.rocketmq.common.protocol.heartbeat.MessageModel
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 24 common frames omitted

请确认下问题，是否可支持JDK17？以及修复方法

**Comment by KouShenhai** [comment]
https://github.com/KouShenhai/KCloud-Platform-Alibaba/tree/master/laokou-common/laokou-common-rocketmq

**Comment by shen-hong-wei** [comment]
> org.apache.rocketmq.spring.autoconfigure.RocketMQAutoConfiguration 自动装配就行

这个已经配置了，只是启动的时候报我上面的异常信息，你启动没有问题嘛？你的项目我看了，目前没发现额外配置，是否可以说明一下JDK17版本maven中针对rocketMQ中引入的配置

**Comment by KouShenhai** [comment]
> > org.apache.rocketmq.spring.autoconfigure.RocketMQAutoConfiguration 自动装配就行
> 
> 这个已经配置了，只是启动的时候报我上面的异常信息，你启动没有问题嘛？你的项目我看了，目前没发现额外配置，是否可以说明一下JDK17版本maven中针对rocketMQ中引入的配置

我目前兼容的版本是5.1.1，目前没有报错

**Comment by shen-hong-wei** [comment]
> > > > > org.apache.rocketmq.spring.autoconfigure.RocketMQAutoConfiguration 自动装配就行
> > > > 
> > > > 
> > > > 这个已经配置了，只是启动的时候报我上面的异常信息，你启动没有问题嘛？你的项目我看了，目前没发现额外配置，是否可以说明一下JDK17版本maven中针对rocketMQ中引入的配置
> > > 
> > > 
> > > 我目前兼容的版本是5.1.1，目前没有报错
> > > ![image](https://private-user-images.githubusercontent.com/48756217/288943816-25032de8-747c-490b-89c9-a95dcda6f498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDI0OTcsIm5iZiI6MTcwMjAwMjE5NywicGF0aCI6Ii80ODc1NjIxNy8yODg5NDM4MTYtMjUwMzJkZTgtNzQ3Yy00OTBiLTg5YzktYTk1ZGNkYTZmNDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAyMjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NDUyYmQzNmVjNjcxZGY1M2ViM2U1ZmIxMWEzZGJiOWM2MzU1MTRmOTE4YWMzMjZjODAxYmY1YWQyZDczZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cLEs5v5GHdbnSJZd7bg-JJYjq03TdOy6pnpOX_S8jTI) 你这个错误明显是依赖缺失了
> > 
> > 
> > 所以你那边额外引入了什么依赖嘛？
> 
> 没有额外引入依赖

很奇怪，我也是引入了同版本的starter

**Comment by shen-hong-wei** [comment]
> 部署到生产环境没有什么问题，有可能是我集成了spring-cloud-alibaba，alibaba的依赖有这个相似的依赖把

是否可以给我看一下你的springboot版本以及下图中的rocketmq相关依赖版本，我发现缺失的类位于rocketmq-comon中，目前是在starter中强制指定了这个类，但是依赖rocketmq-common版本中并没有这个类，在低版本中确实是存在的
![image](https://github.com/apache/rocketmq-spring/assets/123622618/0811bb73-4232-491c-a658-813ec780edf4)

**Comment by KouShenhai** [comment]
😂明天看看

**Comment by KouShenhai** [comment]
![image](https://github.com/apache/rocketmq-spring/assets/48756217/dd13b115-76d0-42e8-8582-34392c2b6060)

**Comment by KouShenhai** [comment]
![image](https://github.com/apache/rocketmq-spring/assets/48756217/a0053a8b-c215-4b79-ad92-e6bab7dae305)

**Comment by shen-hong-wei** [comment]
> ![image](https://private-user-images.githubusercontent.com/48756217/290207482-a0053a8b-c215-4b79-ad92-e6bab7dae305.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5Nzk3NzksIm5iZiI6MTcwMjk3OTQ3OSwicGF0aCI6Ii80ODc1NjIxNy8yOTAyMDc0ODItYTAwNTNhOGItYzIxNS00Yjc5LWFkOTItZTZiYWI3ZGFlMzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE5VDA5NTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZmMxMTNhNzNhNzMzNTgyZmVhYmI0NDhjYzczZDhhMjAyM2EzMDcwZmNhYTQzM2M1Mzg0MWQwYjMxM2MzMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.14dKraVKeyBwhvCIW1o6ELfp0VxpRlTiYzjdEtfFISM)

我发现问题了，是指定了rocketmq子依赖的版本，导致版本之间没有拉齐导致的，根本问题还是父子工程，目前没问题了

**Comment by KouShenhai** [comment]
ok,ok

**Comment by yanglaiyi** [comment]
请问楼主最后是怎么解决的呀

**Comment by KouShenhai** [comment]
> 请问楼主最后是怎么解决的呀

你现在还有这种问题？

**Comment by shen-hong-wei** [comment]
@yanglaiyi @KouShenhai 没有问题了，我当时是依赖中指定了rocketmq子依赖的版本，导致版本之间没有拉齐导致的，根本问题还是父子工程，通常不要指定starter中的子版本，再加上增加一个org.apache.rocketmq.spring.autoconfigure.RocketMQAutoConfiguration 自动装配就行

**Comment by yanglaiyi** [comment]
您好，是的，我使用的是jdk17+spring-cloud-starter-stream-rocketmq 2023.0.0.0-RC1+ srpingcloud alibaba 2022.0.0.0

**Comment by yanglaiyi** [comment]
如果我们spring-stream-rocketmq的版本降为2022.0.0 那么就不会有这个错误

**Comment by yanglaiyi** [comment]
项目在启动的时候并没有任何问题，但是用producer进行发送消息的时候就会报这个错误
![image](https://github.com/apache/rocketmq-spring/assets/66899276/10ba923c-7004-4f79-a665-479a1c447b66)

**Comment by KouShenhai** [comment]
应该是依赖冲突啦
![image](https://github.com/apache/rocketmq-spring/assets/48756217/1989d756-5230-4fb7-a960-d269e8fe8695)
![image](https://github.com/apache/rocketmq-spring/assets/48756217/2ea9845f-0e80-460b-b77d-09e1319d7ac6)

**Comment by KouShenhai** [comment]
我目前使用最新版的，没有发现什么问题，而且我一直频繁更新以阿里技术栈为主流的微服务脚手架

**Comment by yanglaiyi** [comment]
看起来正如您所说的，我引入的23版本，应该是5.1.4，但是这里却是4.9.4.
![image](https://github.com/apache/rocketmq-spring/assets/66899276/e4bd7ce7-9f15-4a92-8cae-74a1df5372c4)
朋友您有有解决问题的建议吗？

**Comment by KouShenhai** [comment]
> 看起来正如您所说的，我引入的23版本，应该是5.1.4，但是这里却是4.9.4. ![image](https://private-user-images.githubusercontent.com/66899276/325836840-e4bd7ce7-9f15-4a92-8cae-74a1df5372c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMDI2OTUsIm5iZiI6MTcxNDEwMjM5NSwicGF0aCI6Ii82Njg5OTI3Ni8zMjU4MzY4NDAtZTRiZDdjZTctOWYxNS00YTkyLThjYWUtNzRhMWRmNTM3MmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDAzMzMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzY2NlZjc3NzYzM2M2YTdhMjNiYjMxNzdmNDIyNGE0ODkyYmM5YjNmMmRlN2Q2NTA0NTMyNDg0MDRiYzAyNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EiNOZpdrZCeKIK-QJFvSD9fy-LJWT-KmLvOiOgSfGbM) 朋友您有有解决问题的建议吗？

直接移除没用的依赖，重新指定依赖

**Comment by yanglaiyi** [comment]
好的，十分感谢您的建议。
