### ISSUE TITLE
aliyun hongkong zone rocketmq carsh

### ISSUE THREAD

**Issue by vodcms** [apache/rocketmq-spring#62]
topic name create and confirm name is right

this.rocketMQTemplate.convertAndSend(QueueNames.TopicName, desc); 

but' send normal message has exception

See http://rocketmq.apache.org/docs/faq/ for further details.; nested exception is org.apache.rocketmq.client.exception.MQClientException: No route info of this topic, xxxx
See http://rocketmq.apache.org/docs/faq/ for further details.

my connectInternet Region rocketmq is ok

**Comment by taroyutao** [comment]
遇到的同样的问题，请问这个开源的SDK是否能够兼容阿里云的Rocket MQ？

**Comment by vodcms** [comment]
我再找阿里云客服处理了

**Comment by walking98** [comment]
从你的想象看，同样的客户端(rocketmq-spring), 对不同的broker服务端现象不一样。应该不是客户端的问题，可能与你连接阿里云香港region的网络配置有关。如果有具体环境，我们可以验证一下。

另外，请把标题改成英文的，所有RMQ的issue提问建议使用英文，至少标题使用英文，谢谢

**Comment by vodcms** [comment]
> 从你的想象看，同样的客户端(rocketmq-spring), 对不同的broker服务端现象不一样。应该不是客户端的问题，可能与你连接阿里云香港region的网络配置有关。如果有具体环境，我们可以验证一下。
> 
> 另外，请把标题改成英文的，所有RMQ的issue提问建议使用英文，至少标题使用英文，谢谢

需要什么那些相关信息？

**Comment by walking98** [comment]
@vodcms 你们具体的调用配置是指配置name-server吗？还是这个公有云访问需要配置配置 AK, SK等信息？如果是纯Aliyun的公网访问方式还需要功能加强一下才能支持，这个我们会在5月份看一下尽快推出。

**Comment by vodcms** [comment]
> @vodcms 你们具体的调用配置是指配置name-server吗？还是这个公有云访问需要配置配置 AK, SK等信息？如果是纯Aliyun的公网访问方式还需要功能加强一下才能支持，这个我们会在5月份看一下尽快推出。

阿里云公网连接没有任何毛病，但是使用香港私有网络连接就出现我提交的问题，AK,SK信息都有的。

我现在遇到在使用公网做项目测试环境，没问题，但是部署到私有网络忘记就崩溃了。导致项目延期，虽然我们可以自己实现整合阿里的私有SDK，不过我觉得咱们这个实现的优雅多了。要赞

**Comment by ShannonDing** [comment]
@vodcms @taroyutao RocketMQ Spring 2.0.3版本已经发布了，支持4.5.1客户端无缝上云， 可以使用新版的spring验证一下了。

**Comment by vongosling** [comment]
@ShannonDing 文档有吗

**Comment by qq592304796** [comment]
@ShannonDing I am using the latest version or will have the same problem

<rocketmq.starter.version>2.0.3</rocketmq.starter.version>
```
rocketmq:
    name-server: XXX.mq-internet-access.mq-internet.aliyuncs.com:80
    access-channel: CLOUD
    producer:
        access-key: XXX
        secret-key: XXX
        group: XXX%XXX
```
```
See http://rocketmq.apache.org/docs/faq/ for further details.; nested exception is org.apache.rocketmq.client.exception.MQClientException: Send [3] times, still failed, cost [1227]ms, Topic: TEST, BrokersSent: [qdinternet-06, qdinternet-05, qdinternet-06]
See http://rocketmq.apache.org/docs/faq/ for further details., mergedContextConfiguration = [MergedContextConfiguration@4f4c4b1a testClass = NativeProducerTest, locations = '{}', classes = '{class com.wjh.common.message.ApplicationTest}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@1d296da, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@557caf28, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@1f2586d6, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@2cd76f31], contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map[[empty]]], class annotated with @DirtiesContext [false] with mode [null], method annotated with @DirtiesContext [false] with mode [null].

org.springframework.messaging.MessagingException: Send [3] times, still failed, cost [1227]ms, Topic: TEST, BrokersSent: [qdinternet-06, qdinternet-05, qdinternet-06]
See http://rocketmq.apache.org/docs/faq/ for further details.; nested exception is org.apache.rocketmq.client.exception.MQClientException: Send [3] times, still failed, cost [1227]ms, Topic: TEST, BrokersSent: [qdinternet-06, qdinternet-05, qdinternet-06]
See http://rocketmq.apache.org/docs/faq/ for further details.

	at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSend(RocketMQTemplate.java:194)
	at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSend(RocketMQTemplate.java:126)
	at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSend(RocketMQTemplate.java:114)
	at org.apache.rocketmq.spring.core.RocketMQTemplate.doSend(RocketMQTemplate.java:514)
	at org.apache.rocketmq.spring.core.RocketMQTemplate.doSend(RocketMQTemplate.java:53)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)
	at com.wjh.common.message.NativeProducerTest.sendMessage(NativeProducerTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.apache.rocketmq.client.exception.MQClientException: Send [3] times, still failed, cost [1227]ms, Topic: TEST, BrokersSent: [qdinternet-06, qdinternet-05, qdinternet-06]
See http://rocketmq.apache.org/docs/faq/ for further details.
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:638)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1310)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:358)
	at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSend(RocketMQTemplate.java:188)
	... 36 more
Caused by: org.apache.rocketmq.client.exception.MQBrokerException: CODE: 1  DESC: com.aliyun.openservices.ons.api.impl.authority.exception.AuthenticationException: valid resource owner failed. maybe the resource TEST not created, com.alibaba.ons.open.auth.validator.PermissionValidator.check(PermissionValidator.java:72)
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:565)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:361)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:343)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:297)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:831)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:557)
	... 39 more
```

aliyun provided ons-client can be used normally
