### ISSUE TITLE
Native-image之后无法连接namesvr,但是在jdk环境里面可以连接

### ISSUE THREAD

**Issue by huyu-tom** [apache/rocketmq-spring#633]
版本：
SpringBoot3.1.6版本 和 rocketmq-spring-boot-starter 2.2.3版本

Native-Image之后错误信息
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRegisterListener': java.lang.IllegalStateException: org.apache.rocketmq.remoting.exception.RemotingSendRequestException: send request to <192.168.192.214:8876> failed
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:605) ~[ai:6.0.14]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[ai:6.0.14]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[ai:6.0.14]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[ai:6.0.14]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[ai:6.0.14]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[ai:6.0.14]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[ai:6.0.14]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:950) ~[ai:6.0.14]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:616) ~[ai:6.0.14]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[ai:3.1.6]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738) ~[ai:3.1.6]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440) ~[ai:3.1.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[ai:3.1.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[ai:3.1.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[ai:3.1.6]
        at com.huyu.App.main(App.java:13) ~[ai:na]
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH) ~[na:na]
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: org.apache.rocketmq.remoting.exception.RemotingSendRequestException: send request to <192.168.192.214:8876> failed
        at org.apache.rocketmq.spring.autoconfigure.ListenerContainerConfiguration.registerContainer(ListenerContainerConfiguration.java:109) ~[ai:na]
        at org.apache.rocketmq.spring.annotation.RocketMQMessageListenerBeanPostProcessor.postProcessAfterInitialization(RocketMQMessageListenerBeanPostProcessor.java:55) ~[ai:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:434) ~[ai:6.0.14]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1773) ~[ai:6.0.14]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[ai:6.0.14]
        ... 16 common frames omitted
Caused by: java.lang.IllegalStateException: org.apache.rocketmq.remoting.exception.RemotingSendRequestException: send request to <192.168.192.214:8876> failed
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:671) ~[ai:5.0.0]
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:500) ~[ai:5.0.0]
        at org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.updateTopicSubscribeInfoWhenSubscriptionChanged(DefaultMQPushConsumerImpl.java:1206) ~[na:na]
        at org.apache.rocketmq.client.impl.consumer.DefaultMQPushConsumerImpl.start(DefaultMQPushConsumerImpl.java:969) ~[na:na]
        at org.apache.rocketmq.client.consumer.DefaultMQPushConsumer.start(DefaultMQPushConsumer.java:737) ~[na:na]
        at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.start(DefaultRocketMQListenerContainer.java:343) ~[ai:2.2.3]
        at org.apache.rocketmq.spring.autoconfigure.ListenerContainerConfiguration.registerContainer(ListenerContainerConfiguration.java:106) ~[ai:na]
        ... 20 common frames omitted
Caused by: org.apache.rocketmq.remoting.exception.RemotingSendRequestException: send request to <192.168.192.214:8876> failed
        at org.apache.rocketmq.remoting.netty.NettyRemotingAbstract.invokeSyncImpl(NettyRemotingAbstract.java:436) ~[ai:5.0.0]
        at org.apache.rocketmq.remoting.netty.NettyRemotingClient.invokeSync(NettyRemotingClient.java:455) ~[na:na]
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1785) ~[na:na]
        at org.apache.rocketmq.client.impl.MQClientAPIImpl.getTopicRouteInfoFromNameServer(MQClientAPIImpl.java:1776) ~[na:na]
        at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:610) ~[ai:5.0.0]
        ... 26 common frames omitted

本地使用JDK:
 a producer (ai-project) init on namesrv 192.168.192.214:8876
2024-02-26T22:52:24.294+08:00  INFO 25819 --- [           main] a.r.s.s.DefaultRocketMQListenerContainer : running container: DefaultRocketMQListenerContainer{consumerGroup='close-order-group', namespace='', nameServer='192.168.192.214:8876', topic='ORDER_CLOSE_TOPIC', consumeMode=CONCURRENTLY, selectorType=TAG, selectorExpression='*', messageModel=CLUSTERING', tlsEnable=false, instanceName=DEFAULT}
2024-02-26T22:52:24.294+08:00  INFO 25819 --- [           main] o.a.r.s.a.ListenerContainerConfiguration : Register the listener to container, listenerBeanName:orderCloseListener, containerBeanName:org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer_1
2024-02-26T22:52:24.325+08:00  INFO 25819 --- [           main] a.r.s.s.DefaultRocketMQListenerContainer : running container: DefaultRocketMQListenerContainer{consumerGroup='user-register-group', namespace='', nameServer='192.168.192.214:8876', topic='USER_REGISTER_SUCCESS_TOPIC', consumeMode=CONCURRENTLY, selectorType=TAG, selectorExpression='*', messageModel=CLUSTERING', tlsEnable=false, instanceName=DEFAULT}
2024-02-26T22:52:24.325+08:00  INFO 25819 --- [           main] o.a.r.s.a.ListenerContainerConfiguration : Register the listener to container, listenerBeanName:userRegisterListener, containerBeanName:org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer_2
就可以连接成功

**Comment by huyu-tom** [comment]
> 你好，这个问题你有解决吗

fastjson和fastjson2引起的反序列化异常, 主要是fastjson和fastjson2在native-image的bug,https://github.com/alibaba/fastjson2/issues/3108  这个错误的导致的

**Comment by tangtang-zhou** [comment]
发送不包含布尔值的消息也会出现相同的问题

**Comment by huyu-tom** [comment]
> 发送不包含布尔值的消息也会出现相同的问题
> 
> [2025-07-29 16:22:54.520] [ERROR] [95c702d36f964bc7bdd697b19959144a] [http-nio-18899-exec-1] o.a.r.s.c.RocketMQTemplate:698 - syncSend failed. destination:UZ-UA-SLAB, message:GenericMessage [payload=byte[23], headers={contentType=text/plain;charset=UTF-8, id=8a15004f-717f-383e-668b-d237d07dddfc, timestamp=1753777374133}], detail exception info: java.lang.IllegalStateException: org.apache.rocketmq.remoting.exception.RemotingSendRequestException: send request to </10.180.34.1:9876> failed at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:859) at org.apache.rocketmq.client.impl.factory.MQClientInstance.updateTopicRouteInfoFromNameServer(MQClientInstance.java:576) at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.tryToFindTopicPublishInfo(DefaultMQProducerImpl.java:892) at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendDefaultImpl(DefaultMQProducerImpl.java:750) at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1603) at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:491) at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSend(RocketMQTemplate.java:691) at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSend(RocketMQTemplate.java:487) at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSend(RocketMQTemplate.java:475) at org.apache.rocketmq.spring.core.RocketMQTemplate.doSend(RocketMQTemplate.java:1146) at org.apache.rocketmq.spring.core.RocketMQTemplate.doSend(RocketMQTemplate.java:61) at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:151) at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:129) at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:122) at cn.cisdigital.mv.ocr.webapp.external.mq.rocketmq.publish.ExternalSystemPublishMessageImpl.publish(ExternalSystemPublishMessageImpl.java:25) at cn.cisdigital.mv.ocr.webapp.interfaces.facade.extend.MessageSendApi.rocketmqSend(MessageSendApi.java:58) at java.base@17.0.10/java.lang.reflect.Method.invoke(Method.java:568) at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547) at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) at com.github.xiaoymin.knife4j.extend.filter.basic.JakartaServletSecurityBasicAuthFilter.doFilter(JakartaServletSecurityBasicAuthFilter.java:55) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) at cn.cisdigital.mv.ocr.webapp.infrastructure.config.SaTokenConfigure$MySaServletFilter.doFilter(SaTokenConfigure.java:127) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)

其实你理解错了，不是你发的消息是否有bool，而是在你发送消息的时候会连接namesrv,namesrv会返回queue的地址和路由信息包含了bool,然后反序列化失败的

**Comment by huyu-tom** [comment]
> 你好，最新2.0.58 fastjson2已经修复反序列化问题，请问你这边还有此问题吗。

嗯啊，我知道昨天温少发了最新版本,我没有升级，我之前通过降版本,我用了2.0.22左右的版本是没有这个问题的

**Comment by tangtang-zhou** [comment]
可能是我springboot版本的问题，fastjson替换了2.0.22和2.0.58依旧存在问题，我使用的3.1.4，我看您使用的3.5.3，后续我用您的测试代码试一下。

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `bug` | Status: **Evaluated**

The issue reports that after GraalVM native-image compilation, the application cannot connect to the NameServer, while it works fine in a regular JDK environment.

**Likely Root Cause:** GraalVM native-image requires explicit reflection/configuration for classes that use dynamic features. The RocketMQ remoting layer likely uses reflection or dynamic proxy patterns that are not automatically included in the native image.

**Recommended:**
1. Add RocketMQ remoting classes to the native-image reflection configuration (`-H:ReflectionConfigurationFiles=`)
2. Ensure all network-related classes (Netty, remoting protocol) are included in the native image
3. Check if there are resource files (e.g., protocol serialization configs) that need to be bundled

This is a known category of issues with GraalVM native-image and frameworks that rely on reflection/dynamic class loading.

---
*Automated evaluation by RockteMQ-AI*
