### ISSUE TITLE
the expected type is FIFO, but actual type is NORMAL BROKER

### ISSUE THREAD

**Issue by jevonsnotes** [apache/rocketmq-spring#665]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
send order message
```
 rocketMQTemplate.syncSendOrderly(topic, message, hashKey);
```
- What did you expect to see?
send successful
- What did you see instead?
```
org.apache.rocketmq.client.exception.MQBrokerException: CODE: 13  DESC: TopicMessageType validate failed, the expected type is FIFO, but actual type is NORMAL BROKER: 10.26.22.29:8080
For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.processSendResponse(MQClientAPIImpl.java:774)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessageSync(MQClientAPIImpl.java:610)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:592)
	at org.apache.rocketmq.client.impl.MQClientAPIImpl.sendMessage(MQClientAPIImpl.java:536)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendKernelImpl(DefaultMQProducerImpl.java:1016)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.sendSelectImpl(DefaultMQProducerImpl.java:1309)
	at org.apache.rocketmq.client.impl.producer.DefaultMQProducerImpl.send(DefaultMQProducerImpl.java:1275)
	at org.apache.rocketmq.client.producer.DefaultMQProducer.send(DefaultMQProducer.java:669)
	at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSendOrderly(RocketMQTemplate.java:769)
	at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSendOrderly(RocketMQTemplate.java:745)
	at org.apache.rocketmq.spring.core.RocketMQTemplate.syncSendOrderly(RocketMQTemplate.java:732)
	at picc.spring.rocketmq.helper.RocketMqHelper.syncSendOrderly(RocketMqHelper.java:123)
	at picc.spring.test.server.api.RocketMqApi.lambda$testTopicFIFO$1(RocketMqApi.java:71)
	at picc.spring.test.server.api.RocketMqApi.looper(RocketMqApi.java:82)
	at picc.spring.test.server.api.RocketMqApi.testTopicFIFO(RocketMqApi.java:71)
	at picc.spring.test.server.api.RocketMqApi.test(RocketMqApi.java:40)
	at picc.spring.test.server.api.RocketMqApi$$FastClassBySpringCGLIB$$e0139f33.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
```
2. Please tell us about your environment:
linux 
rocketmq 5.2.0
rocketmq spring 2.3.0
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `type/bug` | Status: **Needs Info**

The error "expected type is FIFO, but actual type is NORMAL BROKER" indicates a mismatch between the consumer's expected message type and the broker's topic type.

To help diagnose this issue, please provide:
- [ ] Starter version and configuration
- [ ] Topic creation method (auto-created or manually created via mqadmin?)
- [ ] Whether the topic was created as FIFO type
- [ ] Consumer annotation configuration (`@RocketMQMessageListener`)

This typically occurs when:
1. The topic was created as NORMAL but the consumer expects FIFO
2. Or the broker configuration doesn't support FIFO message types

**Quick fix:** Ensure the topic is created with `--topic-type FIFO` when using FIFO consumers.

---
*Automated evaluation by RockteMQ-AI*
