### ISSUE TITLE
Consumer thrown an exception, but didn't trigger reconsume, and the message's status was consumed.

### ISSUE THREAD

**Issue by meng-taiqian** [apache/rocketmq-spring#92]
**BUG REPORT**

1. Please describe the issue you observed:
We defined a consumer who will always throw an exception to verify the retry mechanism.
The onMessage method is:
` public void onMessage(MessageExt message) {`
    `int reconsumeTimes = message.getReconsumeTimes();`
    `if(reconsumeTimes==10){//重试10次失败后`
        `log.warn("mq消息处理支付后订单扭转接口mq失败后重试次数达到上限,reconsumeTimes={}",reconsumeTimes);`
        `return;`
    `}`
    `throw FinanceException.warning(FinanceErrorCode.ERR_COMMON_001);`
`}`
we expect the message to be reconsumed, but the result is as title described.

2. Please tell us about your environment:
The cluster use the 2m-noslave mode, and below is the config:

brokerClusterName=Testcluster
brokerName=broker-a
brokerId=0
namesrvAddr=rocketmq-master1.vvip-u.com:9876;rocketmq-master2.vvip-u.com:9876
defaultTopicQueueNums=4
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
listenPort=10911
deleteWhen=04
fileReservedTime=120
mapedFileSizeCommitLog=1073741824
mapedFileSizeConsumeQueue=300000
diskMaxUsedSpaceRatio=88
storePathRootDir= /usr/local/rocketmq/store
storePathCommitLog= /usr/local/rocketmq/store/commitlog
storePathConsumeQueue=/usr/local/rocketmq/store/consumequeue
storePathIndex=/usr/local/rocketmq/store/index
storeCheckpoint=/usr/local/rocketmq/store/checkpoint
maxMessageSize=65536
brokerRole=ASYNC_MASTER

**Comment by ShannonDing** [comment]
Maybe It is better to share the exception message or some log here.

**Comment by meng-taiqian** [comment]
2019-06-19 16:37:59.361 [ConsumeMessageThread_11] WARN  o.a.r.s.support.DefaultRocketMQListenerContainer - consume message failed. messageExt:MessageExt [queueId=1, storeSize=459, queueOffset=38, sysFlag=0, bornTimestamp=1560933479345, bornHost=/xx.xx.xx.xx:41200, storeTimestamp=1560933477885, storeHost=/xx.xx.xx.xx:10911, msgId=0A1C117900002A9F000000000045CD3A, commitLogOffset=4574522, bodyCRC=1545627141, reconsumeTimes=0, preparedTransactionOffset=0, toString()=Message{topic='taxi_order_payoff_fail', flag=0, properties={MIN_OFFSET=0, MAX_OFFSET=39, CONSUME_START_TIME=1560933479352, id=8a48eb84-c9f3-ba63-672a-c791c8e9ce4a, UNIQ_KEY=0A1C21BD30792285B40C604427B10049, WAIT=false, contentType=text/plain, TAGS=taxi_order_payoff_fail_tags, timestamp=1560933479344}, body=[123, 34, 111, 114, 100, 101, 114, 73, 100, 34, 58, 50, 56, 48, 52, 48, 50, 57, 53, 50, 56, 55, 57, 57, 54, 53, 54, 55, 44, 34, 112, 97, 121, 84, 121, 112, 101, 34, 58, 34, 79, 70, 70, 95, 76, 73, 78, 69, 34, 44, 34, 112, 97, 121, 67, 104, 97, 110, 110, 101, 108, 34, 58, 34, 79, 70, 70, 76, 73, 78, 69, 95, 80, 65, 89, 34, 44, 34, 111, 114, 100, 101, 114, 65, 109, 111, 117, 110, 116, 34, 58, 110, 117, 108, 108, 44, 34, 112, 97, 121, 65, 109, 111, 117, 110, 116, 34, 58, 57, 48, 48, 44, 34, 112, 97, 121, 84, 105, 109, 101, 34, 58, 34, 50, 48, 49, 57, 45, 48, 54, 45, 49, 57, 84, 48, 56, 58, 51, 55, 58, 53, 57, 46, 50, 57, 48, 43, 48, 48, 48, 48, 34, 44, 34, 112, 108, 97, 116, 102, 111, 114, 109, 84, 121, 112, 101, 34, 58, 110, 117, 108, 108, 125], transactionId='null'}]
com.xx.xx.service.finance.exception.FinanceException: 服务器繁忙
	at com.xx.xx.service.finance.exception.FinanceException.warning(FinanceException.java:63)
	at com.xx.xx.finance.mq.OrderPayoffHandler.onMessage(OrderPayoffHandler.java:40)
	at com.xx.xx.finance.mq.OrderPayoffHandler.onMessage(OrderPayoffHandler.java:18)
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer$DefaultMessageListenerConcurrently.consumeMessage(DefaultRocketMQListenerContainer.java:308)
	at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:417)

**Comment by vongosling** [comment]
@meng-taiqian I am quite disgusted with the no sign of the problem :-( , please use the latest version to verify whether there is such a problem, and I am very glad to hear your further feedback again.
