### ISSUE TITLE
Use Consumer Sample, Stop Applying Exception

### ISSUE THREAD

**Issue by stillChina** [apache/rocketmq-spring#93]

**Comment by stillChina** [comment]
Disconnected from the target VM, address: '127.0.0.1:50895', transport: 'socket'
2019-06-20 14:04:06.105  WARN 10656 --- [      Thread-20] o.s.c.support.DefaultLifecycleProcessor  : Failed to stop bean 'org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer_1'

java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82) ~[na:1.8.0_201]
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239) ~[na:1.8.0_201]
	at org.apache.rocketmq.client.trace.AsyncTraceDispatcher.removeShutdownHook(AsyncTraceDispatcher.java:219) ~[rocketmq-client-4.5.1.jar:4.5.1]
	at org.apache.rocketmq.client.trace.AsyncTraceDispatcher.shutdown(AsyncTraceDispatcher.java:192) ~[rocketmq-client-4.5.1.jar:4.5.1]
	at org.apache.rocketmq.client.consumer.DefaultMQPushConsumer.shutdown(DefaultMQPushConsumer.java:710) ~[rocketmq-client-4.5.1.jar:4.5.1]
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.stop(DefaultRocketMQListenerContainer.java:268) ~[rocketmq-spring-boot-2.0.3.jar:2.0.3]
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.stop(DefaultRocketMQListenerContainer.java:244) ~[rocketmq-spring-boot-2.0.3.jar:2.0.3]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:238) [spring-context-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:53) [spring-context-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:377) [spring-context-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:210) [spring-context-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:128) [spring-context-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1005) [spring-context-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:933) [spring-context-5.1.0.RELEASE.jar:5.1.0.RELEASE]

2019-06-20 14:04:36.912  INFO 10656 --- [      Thread-20] o.s.c.support.DefaultLifecycleProcessor  : Failed to shut down 1 bean with phase value 2147483647 within timeout of 30000: [org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer_1]
2019-06-20 14:04:36.912  INFO 10656 --- [      Thread-20] a.r.s.s.DefaultRocketMQListenerContainer : container destroyed, DefaultRocketMQListenerContainer{consumerGroup='string_trans_consumer', nameServer='127.0.0.1:9876', topic='spring-transaction-topic', consumeMode=CONCURRENTLY, selectorType=TAG, selectorExpression='*', messageModel=CLUSTERING}
2019-06-20 14:04:36.913  INFO 10656 --- [      Thread-20] a.r.s.s.DefaultRocketMQListenerContainer : container destroyed, DefaultRocketMQListenerContainer{consumerGroup='string_consumer', nameServer='127.0.0.1:9876', topic='string-topic', consumeMode=CONCURRENTLY, selectorType=TAG, selectorExpression='*', messageModel=CLUSTERING}
2019-06-20 14:04:36.913  INFO 10656 --- [      Thread-20] a.r.s.s.DefaultRocketMQListenerContainer : container destroyed, DefaultRocketMQListenerContainer{consumerGroup='string_consumer', nameServer='127.0.0.1:9876', topic='string-topic', consumeMode=CONCURRENTLY, selectorType=TAG, selectorExpression='*', messageModel=CLUSTERING}
2019-06-20 14:04:36.913  INFO 10656 --- [      Thread-20] a.r.s.s.DefaultRocketMQListenerContainer : container destroyed, DefaultRocketMQListenerContainer{consumerGroup='order-paid-consumer', nameServer='127.0.0.1:9876', topic='order-paid-topic', consumeMode=CONCURRENTLY, selectorType=TAG, selectorExpression='*', messageModel=CLUSTERING}
2019-06-20 14:04:36.914  INFO 10656 --- [      Thread-20] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer_1': java.lang.IllegalStateException: Shutdown in progress

**Comment by Lzw2016** [comment]
这个问题怎么解决

**Comment by Lzw2016** [comment]
How to solve this problem? Shut it down without saying anything?

**Comment by Maoxianzhe** [comment]
经过排查问题,应该是版本对应问题,我这里是spring-boot-starter:2.2.4.RELEASE,当关闭应用时,会有异常抛出,然后查看mvnrepository,应该使用rocketmq-spring-boot:2.2.1,这个版本支持spring-boot-starter:2.0.5.RELEASE之后的版本,要注意一个问题,rocketmq-spring-boot-starter:2.0.0以上,包含了rocketmq-client的包,不需要再引入了,如果引入rocketmq-client版本低于4.6.0,还会有异常抛出
